spring:
  h2:
    console:
      enabled: true
      #path: /h2-console # Example with default value: http://localhost:8080/h2-console
  datasource:
    url: "jdbc:h2:mem:fastbookdb;DB_CLOSE_DELAY=-1" # in-memory storage; keep connection
    initialization-mode: embedded # automatyically init only for embedded DB

# Logging levels
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG # Log SQL statements
    org.hibernate.type.descriptor.sql: TRACE

       
